version: "3"
services:
  rq1:
    image: smart_selection_analysis
    volumes:
     - "./experimental_data:/exp"
    command: "/analysis/bin/smart_selection_analysis -f /exp/data_folder -b /exp/b1 -q 1"
  rq2:
    image: smart_selection_analysis
    volumes:
      - "./experimental_data:/exp"
    command: "/analysis/bin/smart_selection_analysis -f /exp/data_folder -b /exp/b1 -q 2"
  rq3:
    image: smart_selection_analysis
    volumes:
      - "./experimental_data:/exp"
    command: "/analysis/bin/smart_selection_analysis -f /exp/data_folder -b /exp/b1 -q 3"
  rq5:
    image: smart_selection_analysis
    volumes:
      - "./experimental_data:/exp"
    command: "/analysis/bin/smart_selection_analysis  -f /exp/data_folder -b /exp/b1 -q 5"
  rq6:
    image: smart_selection_analysis
    volumes:
      - "./experimental_data:/exp"
    command: "/analysis/bin/smart_selection_analysis  -f /exp/data_folder -b /exp/b1 -q 6"